CREATE TABLE USERS (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR ( 100 ) NOT NULL,
	surname VARCHAR ( 100 ) NOT NULL
);

CREATE TABLE FILM (
	id INTEGER PRIMARY KEY NOT NULL,
	title VARCHAR ( 50 ) NOT NULL,
	description VARCHAR ( 250 ) NOT NULL
);

CREATE TABLE ROOM (
	id INTEGER PRIMARY KEY NOT NULL,
	numberRoom INTEGER NOT NULL,
	description VARCHAR ( 250 ) NOT NULL
);

CREATE TABLE RESERVATION (
	id INTEGER PRIMARY KEY NOT NULL
);